name: Redeem Gift Code

on:
  workflow_dispatch:
    inputs:
      gift_code:
        description: "Gift Code"
        required: true
        type: string

jobs:
  redeem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show Python Version
        run: python --version

      - name: Redeem Gift Code
        run: |
          python redeem.py "${{ github.event.inputs.gift_code }}"
